### ISSUE TITLE
Help Wanted on professors profile

### ISSUE THREAD

**Issue by frchnrzm** [avuletica/eLearning#10]
hello, i have a problem on professor profile, at the chapter name i can not be clicked, the message is DoesNotExist at /courses/professor/Course object/test1/
Chapter matching query does not exist.

**Comment by shreyansh21996** [comment]
hello, i have a problem on professor profile, at the chapter name i can not be clicked, the message is DoesNotExist at /courses/professor/Course object/test1/
Chapter matching query does not exist.

**Comment by ivaniclixx** [comment]
The same happened to me. The "Course object" gave me the hint: the system is not getting the name of the course when using the object directly. So I checked the models.py file and found out the problem: the code is using the old "def __unicode__" method (Python 2) and I am using Python 3. The fix is easy: edit models.py and replace "def __unicode__" with "def __str__", and It will work.

**Comment by avuletica** [comment]
I see plenty of people having issues using the newer Python version, please refer to:

https://github.com/avuletica/eLearning#compatibility
